import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Navbar from "@/components/container/Navbar";
import Footer from "@/components/container/Footer";
import { MovieProvider } from "@/context/movieContext";
import { Providers } from "@/query/providers";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <MovieProvider>
          <Navbar />
          <body className={`${poppins.variable} font-sans antialiased`}>
            {children}
          </body>
          <Footer />
        </MovieProvider>
      </Providers>
    </html>
  );
}
