import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Navbar from "@/components/container/Navbar";
import Footer from "@/components/container/Footer";
import { MovieProvider } from "@/context/movieContext";
import { Providers } from "@/query/providers";
import { SearchProvider } from "@/context/searchContext";
import { FavoritesProvider } from "@/context/favoritesContext";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans antialiased`}>
        <SearchProvider>
          <FavoritesProvider>
            <Providers>
              <MovieProvider>
                <Navbar />
                {children}
                <Footer />
              </MovieProvider>
            </Providers>
          </FavoritesProvider>
        </SearchProvider>
      </body>
    </html>
  );
}
